"use strict";
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) result[k] = mod[k];
    result["default"] = mod;
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
const mongoose = __importStar(require("mongoose"));
const project_1 = require("./../models/project");
const user_1 = require("./../models/user");
const ticket_1 = require("./../models/ticket");
const admin_1 = require("./../models/admin");
const comment_1 = require("./../models/comment");
const history_1 = require("./../models/history");
exports.Project = mongoose.model("project", project_1.projectSchema);
exports.User = mongoose.model("user", user_1.userSchema);
exports.Ticket = mongoose.model("ticket", ticket_1.ticketSchema);
exports.History = mongoose.model("history", history_1.historySchema);
exports.Admin = mongoose.model("admin", admin_1.adminSchema);
exports.Comment = mongoose.model("comment", comment_1.commentSchema);
